name: CI
on:
    push:
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: bakerkretzmar/cd-public-test-action@v2
              env:
                ACTIONS_STEP_DEBUG: true
              with:
                milliseconds: 3000
