name: CI
on:
    push:
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: culturedays/cd-public-test-action@v1
              env:
                ACTIONS_STEP_DEBUG: true
              with:
                milliseconds: 2000
